# Generated by Django 5.0 on 2024-01-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=240, verbose_name='Song')),
                ('artist', models.CharField(max_length=240, verbose_name='artist')),
                ('streamed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
