# Generated by Django 5.0 on 2024-01-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='streamed',
            field=models.DateField(),
        ),
    ]
