# Generated by Django 5.0 on 2024-01-03 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_songs_streamed'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
